### ISSUE TITLE
Class Viewer > Delete Your Class -- No state change on rollover, perhaps make it a button

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#102]
STEPS TO REPRODUCE:

Log into Instructor Dashboard
Click any class
Rollover over Delete Your Class
Rollover Add Students for comparison

RESULTS
Delete Your Class does not show a state change on rollover. Other functions on the page.
![image](https://user-images.githubusercontent.com/5755393/108191408-f1a72d00-70c7-11eb-8a26-70a2c9520506.png)

EXPECTED RESULTS Have Delete Your Class change state when rolled over (perhaps make it a button).

**Comment by dunghuynhtrung1987** [comment]
<img width="1005" alt="Screen Shot 2021-02-18 at 9 04 14 PM" src="https://user-images.githubusercontent.com/48272651/108368353-ec172780-722c-11eb-8bdf-a230ba33819f.png">
I make "Delete Your Class" look like button "Add Students". That is request to update?
if it correct Pls PR
https://github.com/khailamconsulting/khailamconsulting.github.io/pull/111
