### ISSUE TITLE
Change the footer

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#103]
Footer shows Contact Us & Legal instead of Contact Us, Privacy Policy, & Terms of Service
STEPS TO REPRODUCE:

Login to Simserver
Check page footer
Click Instructor button
Check page footer

  EXPECTED RESULTS
Contact Us, Privacy Policy, & Terms of Service
Add underlines for rollover on clickable items

Contact Us -> /contact
Privacy Policy -> /privacy
Terms of Service -> /tos

**Comment by dunghuynhtrung1987** [comment]
https://github.com/khailamconsulting/khailamconsulting.github.io/pull/109

**Comment by pmquan** [comment]
Add underlines for rollover on clickable items doesn't work correctly.

The text should be displayed without the underlines. The underlines only appear when a user rollover the pointer over it.

This effect should apply to every single clickable text lines (Eg: Logout, Footers, Edit button, and the Class name)

**Comment by accdungh** [comment]
Pls PR https://github.com/khailamconsulting/khailamconsulting.github.io/pull/122 
Thanks.
