### ISSUE TITLE
Class Viewer -- Make "Summary" header blue like other headers

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#104]
STEPS TO REPRODUCE:

Log in to Instructor Dashboard
Click on any class

RESULTS  
The header "Summary" is in grey text, other headers are blue text.

![image](https://user-images.githubusercontent.com/5755393/108191837-76924680-70c8-11eb-9d8b-ed053d35ab04.png)

**Comment by dunghuynhtrung1987** [comment]
Pls, PR
https://github.com/khailamconsulting/khailamconsulting.github.io/pull/108
