### ISSUE TITLE
Class Name -- Add a character limit to class names

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#105]
Class Name -- Add a character limit to class names
STEPS TO REPRODUCE:

Log in as an instructor
Click Create a New Class button
Under "Add a title for your class" enter characters

RESULTS
There appears to be no realistic limit to the number of characters here
EXPECTED RESULTS
Limit class names to a reasonable length (128 chars) ?

**Comment by namduongkh** [comment]
@pmquan PR? pls https://github.com/khailamconsulting/khailamconsulting.github.io/pull/110
