### ISSUE TITLE
Edit Class -- Popup collapses if user hits DELETE key

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#106]
STEPS TO REPRODUCE:

Login as an Instructor
Click on an existing class
Click Edit button
Click inside the class name text field
Select all the class name in the text field
Click Delete key to remove existing name

RESULTS
Text box collapses to a single line bar. X button is still present.
If the user closes it and tries to reopen it, it will still appear as a single line
Edit function is restored if user leaves and returns to this screen
EXPECTED RESULTS
Text inside box should be deleted
Popup should not collapse

**Comment by namduongkh** [comment]
@pmquan This issue fixed in https://github.com/khailamconsulting/khailamconsulting.github.io/pull/110
