### ISSUE TITLE
Implement the Archived Classes tab

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#107]
The Archived Classes tab:
Data from /api/instructor/class/list (reuse the previous request)
"data": {
    "archivedClasses": { .. }
}

Layout: same as Active Classes
+ Don't display the create a new class button
+ Click on the class will jump to the Class View tab in Read Only mode (without Edit, Add Students, Delete Class, Add Course)

**Comment by namduongkh** [comment]
@pmquan In API class detail, we need to know this class is archived or not to show the corresponding UI
