### ISSUE TITLE
Courses > Course Objectives Line up table header "Skills" with text underneath

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#113]
[InstructorDashboard] Courses > Course Objectives  Line up table header "Skills" with text underneath
STEPS TO REPRODUCE:

Login as Instructor
Click on any class
Click on any Course to reveal Course Objectives
Expand any conversation

RESULTS
Following the CEFR statements there is a table with the headers Objectives and Skills
The header skills is too far to the left and does not line up with the text underneath it

EXPECTED RESULTS Place the Skills header so it lines up correctly with the text below it in the column.

![image](https://user-images.githubusercontent.com/5755393/109149744-d6b66780-771c-11eb-9277-c7cd3ead1d7e.png)

**Comment by dunghuynhtrung1987** [comment]
PR? pls https://github.com/khailamconsulting/khailamconsulting.github.io/pull/118
