### ISSUE TITLE
Create a New Class -- Choosing today's date gets message "Start Date should not be before today"

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#114]
[InstructorDashboard] Create a New Class -- Choosing today's date gets message "Start Date should not be before today"
STEPS TO REPRODUCE:
1.Log in as Instructor
2. Click Create a New Class
3. Elect today's date as a start date
RESULTS
User receives message
Start Date should not be before today

  EXPECTED RESULTS
User should be able to create a class starting today

![image](https://user-images.githubusercontent.com/5755393/109149902-06656f80-771d-11eb-985c-35f81b774db2.png)

**Comment by namduongkh** [comment]
@pmquan 
I have fixed, please check
<img width="768" alt="Screen Shot 2021-02-27 at 10 28 24 AM" src="https://user-images.githubusercontent.com/17775345/109374266-930f5980-78e6-11eb-811a-1c79a9140e86.png">

**Comment by pmquan** [comment]
I just reviewed this error and noticed now the validation is not working correctly.

Example 1

1. Log in as an Instructor and open Instructor Dashboard
2. Click Create A New Class
3. Enter class name and select institution
4. Click calendar and enter an end date, click Add Courses button
5. Receive messages:The Start Date field is required. The End Date field is required.
6. Click calendar and enter a start date, click Add Courses button
7. Same messages remain onscreen, user cannot proceed
8. Click calendar and enter another end date
9. Receive messages:The Start Date field is required.Start Date should not be before End Date
10. Click calendar and enter another start date
11. Receive message: Start Date should not be before End Date
12. Change both start and end date to appropriate values, click Add Courses button
13. User proceeds to next screen

Example 2

1. Fill all the fields. Put wrong Start Date but a correct End Date.
2. Hit Add Courses button. Error message will appear.
3. Correct the Start Date. Hit Add Courses button. The error "The End Date field is required." will still appear.
4. Choose Incorrect Start Date again. Then pick an end date. Then hit Add Courses button. It will process to the next screen.

The datepicker is really buggy across the Create/Edit Class modal. Please revise.
