### ISSUE TITLE
Courses -- Play Simulation button does nothing

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#115]
Instructor Dashboard > Courses -- Play Simulation button does nothing

Launch Instructor Dashboard and click on an available class (Alelo QA General Class)
In the Courses table the final column is labelled **Play Simulations** and has a clickable button

Clicking the button does nothing, it should launch the activeCourse.link parameter.

**Comment by dunghuynhtrung1987** [comment]
PR? Pls https://github.com/khailamconsulting/khailamconsulting.github.io/pull/117

**Comment by dunghuynhtrung1987** [comment]
Upate .link property https://github.com/khailamconsulting/khailamconsulting.github.io/pull/120
