### ISSUE TITLE
Suggestion on the Class View tab

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#116]
I just discussed with the QA & Project Manager. The current layout has 3 tab: Active Class, Class View, and Archived Class. It is a little bit confusion and odd that we have a "Class View" tab here. 

So I suggest them remove the permanent Class View tab here, so the user wont be able to click on it on page load.

Do you guys have any idea or suggestion where we can put the "Class View" view that make more sense? Or shall we hide the Class View tab on the page load and will only appear when the user first clicks on any class ?

**Comment by namduongkh** [comment]
@pmquan sound good
or we just disable the "Class View" tab (can not click) when use did not select any class yet

**Comment by namduongkh** [comment]
PR? https://github.com/khailamconsulting/khailamconsulting.github.io/pull/121
