### ISSUE TITLE
Create/Edit Class -- Add ability for instructor to type date

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#124]
STEPS TO REPRODUCE:

Login as an Instructor
Either Create a New Class or Edit an existing class
Click in the Date fields
Calendar picker appear
Try typing

RESULTS
Typing moves the day forward or backward one day per key press. Does not allow instructor to type date.
EXPECTED RESULTS
Alll instructor to type date

**Comment by namduongkh** [comment]
@pmquan 
Fixed in PR: https://github.com/khailamconsulting/khailamconsulting.github.io/pull/127
<img width="776" alt="Screen Shot 2021-03-06 at 10 49 05 AM" src="https://user-images.githubusercontent.com/17775345/110194157-94ea9700-7e69-11eb-996e-cd10af5934b7.png">
