### ISSUE TITLE
Class Viewer > Edit Class - disallow Instructor to change the Institution

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#125]
STEPS TO REPRODUCE

Log in to the Instructor Dashboard
Complete Create A New Class steps
Go to Class Viewer for Existing Class
Click Edit
The institution displays as a dropdown

RESULTS
The institution displays as a dropdown.
EXPECTED RESULTS
We are not allow instructor to change the class institution anymore. So please just display the institution like a normal text.

Remove Select your institution and the dropdown
Replace with:
Your institution (blue small text)
Institution Name (Bold black text like the dropdown before)

**Comment by namduongkh** [comment]
@pmquan 
Fixed in PR: https://github.com/khailamconsulting/khailamconsulting.github.io/pull/127
<img width="776" alt="Screen Shot 2021-03-06 at 10 49 05 AM" src="https://user-images.githubusercontent.com/17775345/110194157-94ea9700-7e69-11eb-996e-cd10af5934b7.png">
