### ISSUE TITLE
Class Viewer > Resend Invitation -> Need a list of emails to confirm

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#126]
STEPS TO REPRODUCE:

Log in as Instructor and click Instructor button
Click on any class
Select any student(s) and click Resend Invitation

EXPECTED RESULT

Add "Confirmation List" section (Similar to the Course List) with Email as a column (scrollable if more than 2 emails) - to the red rectangle position. 

Reduce the space for the confirmation message.

![image](https://user-images.githubusercontent.com/5755393/110118462-3fca5a80-7d6f-11eb-8f32-211e93d2aa20.png)

**Comment by namduongkh** [comment]
@pmquan 
Fixed in PR: https://github.com/khailamconsulting/khailamconsulting.github.io/pull/127

<img width="774" alt="Screen Shot 2021-03-06 at 10 50 19 AM" src="https://user-images.githubusercontent.com/17775345/110194180-c06d8180-7e69-11eb-8528-404e3d2242b4.png">

For now, I'm using student first name and class name to show in the Confirmation List because the class detail API does not response student email, please add email into the student array

```
"students": [
      {
        "id": "5f35873af5225a544e1e804b",
        "isUser": true,
        "firstName": "750aab0ce80609c0c...",
        "lastName": "1597419111899",
        "lastLogin": "2020-08-14T15:28:49.892Z",
        "totalTime": "00:09:11"
      },
      {
        "id": "5f36ae9cf5225a544e1f18b3",
        "isUser": true,
        "firstName": "ada2588860316511a...",
        "lastName": "1611938781821",
        "lastLogin": "2020-08-14T19:04:00.692Z",
        "totalTime": "00:32:51"
      },
      {
        "id": "58f7ca9d83dfae69f444486f",
        "isUser": true,
        "firstName": "Alelo",
        "lastName": "Superadmin",
        "lastLogin": "2021-03-03T01:04:56.460Z",
        "totalTime": "56:19:01"
      }
```

**Comment by pmquan** [comment]
Sorry, I forgot to push the API build last night. Please recheck. It should have the email field now.

**Comment by namduongkh** [comment]
@pmquan Is the UI OK?
<img width="776" alt="Screen Shot 2021-03-06 at 1 18 30 PM" src="https://user-images.githubusercontent.com/17775345/110197499-78a52500-7e7e-11eb-8d77-1d76a114fd1a.png">

**Comment by pmquan** [comment]
Please hold - waiting for PM to approve the layout

**Comment by namduongkh** [comment]
@pmquan I have a question
When all selected students are the valid user, should display the re-send button or not?
<img width="1005" alt="Screen Shot 2021-03-09 at 8 44 46 PM" src="https://user-images.githubusercontent.com/17775345/110480157-c50b9180-8118-11eb-8bda-c3646d350bbb.png">

**Comment by namduongkh** [comment]
@pmquan 
Please review:
https://github.com/khailamconsulting/khailamconsulting.github.io/pull/130
