### ISSUE TITLE
Notice Modal - Notice message needs to display the raw HTML

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#131]
The HTML message displays incorrectly.

![image](https://user-images.githubusercontent.com/5755393/110683694-296a3780-8191-11eb-8cc8-14aa97e59494.png)

**Comment by namduongkh** [comment]
@pmquan 
I have fixed in https://github.com/khailamconsulting/khailamconsulting.github.io/pull/134/files
please check and feedbak
