### ISSUE TITLE
Missing the player dashboard

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#14]
To reach the player dashboard, go to the "**Class View**" tab, click on the **student name** to go to the **Student summary** page. 
https://lh3.googleusercontent.com/-Lnh7--KT-4k/X4CmrVd7EII/AAAAAAAAD0g/qo22yVvpvB05Ljpr7xUCzkvwZDZT_Hf7QCK8BGAsYHg/s0/2020-10-09.png

Then when you click on the simulation name, the player detailed information dashboard will pop up.
https://lh3.googleusercontent.com/-UD4Hc_btRug/X4Cm08fwDUI/AAAAAAAAD0k/JI7JCx31sVsZmJkCEz0hcT--XSFHWoa8ACK8BGAsYHg/s0/2020-10-09.png

**Comment by rauxalach** [comment]
@dunghuynhtrung1987 This screen is 1.4.10 in https://docs.google.com/spreadsheets/d/1OrenXxgEd40Qvi7PezVrSaxOBATYJ1ZkyhBD-smaKDY/edit#gid=0

**Comment by rauxalach** [comment]
@dunghuynhtrung1987 Player dashboard still doesnt work
