### ISSUE TITLE
Start - End dates error messages

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#24]
The error is now in place if the end date is before the start date, but the message is "Start Date shouldn't greater than End Date." Can we change the message to "Start Date should not be before End Date." ?

It should be updated anywhere having start - end date

**Comment by dunghuynhtrung1987** [comment]
Fixed
<img width="689" alt="Screen Shot 2020-10-14 at 2 40 17 PM" src="https://user-images.githubusercontent.com/48272651/95958339-36c20680-0e2b-11eb-8793-8152aeed77fd.png">
<img width="591" alt="Screen Shot 2020-10-14 at 2 39 45 PM" src="https://user-images.githubusercontent.com/48272651/95958346-3a558d80-0e2b-11eb-8577-ebd880a6b9c1.png">
