### ISSUE TITLE
Class Viewer - Margins and different states

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#25]
"Per the XD mockups (unless something has changed that I'm not aware of), the ""add students"" button should disappear when a current student is checked. Currently that button remains available alongside the ""Remove Student(s) / Resend Invitation(s) Buttons.""

Also - When more than one button is visible, we'll need margins between them. The XD mockup lays out a 32px margin between elements."

<img width="856" alt="Screen Shot 2020-10-14 at 12 00 08 AM" src="https://user-images.githubusercontent.com/1320349/95894543-73521b80-0db3-11eb-9743-9fa122ecc4c4.png">

**Comment by dunghuynhtrung1987** [comment]
Fixed
<img width="1038" alt="Screen Shot 2020-10-14 at 2 32 56 PM" src="https://user-images.githubusercontent.com/48272651/95957781-5b69ae80-0e2a-11eb-9406-4403a40b7e58.png">
