### ISSUE TITLE
Logout Button Adjustment

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#27]
Current:
Link is currently biased toward the top of the container.

Acceptance Requirement:
The link should be vertically center-justified.

Current:
<img width="282" alt="Screen Shot 2020-10-14 at 12 06 26 AM" src="https://user-images.githubusercontent.com/1320349/95894709-ac8a8b80-0db3-11eb-9248-b788a56fa5be.png">

Acceptance:
<img width="206" alt="Screen Shot 2020-10-14 at 12 06 30 AM" src="https://user-images.githubusercontent.com/1320349/95894717-af857c00-0db3-11eb-8d25-d7e3c017da45.png">

**Comment by dunghuynhtrung1987** [comment]
Fixed
![Uploading Screen Shot 2020-10-14 at 2.38.59 PM.png…]()
