### ISSUE TITLE
Student Summary - Course List

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#28]
Currently the top left corner of the course list is rounded (to match the other 3 corners), but that disconnects the course list from the tabs. If possible, can we make the top left corner square, so it connects visually to the tabs?

Tab design
<img width="264" alt="Screen Shot 2020-10-14 at 12 26 33 AM" src="https://user-images.githubusercontent.com/1320349/95894871-ef4c6380-0db3-11eb-9af2-c8a85ea418e1.png">

**Comment by dunghuynhtrung1987** [comment]
Fixed
<img width="1097" alt="Screen Shot 2020-10-14 at 2 43 02 PM" src="https://user-images.githubusercontent.com/48272651/95958610-95878000-0e2b-11eb-983a-e312d95de026.png">
