### ISSUE TITLE
Student Summary - Tooltips and hover text

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#29]
Currently the leader arrow of the tool tips is black, whereas the container is gray. Both should be gray (as is the current design of the same element on the Class Viewer page).

<img width="540" alt="Screen Shot 2020-10-14 at 12 27 48 AM" src="https://user-images.githubusercontent.com/1320349/95894969-1c991180-0db4-11eb-9e65-3f4507e2609e.png">

**Comment by dunghuynhtrung1987** [comment]
I have fixed
![Uploading Screen Shot 2020-10-14 at 2.36.23 PM.png…]()
