### ISSUE TITLE
Display user's first & lastname

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#43]
Please use first, last field from /user/info API to display the welcome banner.

Currently, it is fixed to Welcome, Walter Mitchell!

Should be: Welcome, First Last!
![image](https://user-images.githubusercontent.com/5755393/99774437-9f537180-2ac2-11eb-8246-aac915b5ce4a.png)

Also, when you pull the /user/info, it can be reused for the Settings tab - no need to pull it again.

API URL: https://sim-dev.alelo.com/api/dummy_instructor/user/info

**Comment by namduongkh** [comment]
@pmquan @rauxalach 
PR: https://github.com/khailamconsulting/khailamconsulting.github.io/pull/44
