### ISSUE TITLE
ClassViewer table sort didn't work

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#47]
Step to reproduce:
Test URL: /instructor/#/class/5fb4ecb4198cbfb6f2f4bfbb/student/5835f365605ac81c473ffbcc
Use course: Refresher English - as a test.
Click the sort indicator doesn't work.

Expect:
The table should be sorted on click.

Enhancement:
Please sort by the course (simulation.title) on page load.

**Comment by namduongkh** [comment]
@pmquan 
Worked
Could you please take a look and close?
