### ISSUE TITLE
ClassViewer modal popup

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#48]
The simulation detail view must have the sort function.
Sort by the date (attempt.date) by default.

Only display the last 10 attempts with a paginate navigation.

**Comment by namduongkh** [comment]
@pmquan 
Worked
Could you please take a look and close?

**Comment by pmquan** [comment]
Try this: /instructor/#/class/5fb4ecb4198cbfb6f2f4bfbb/student/5835f365605ac81c473ffbcc
Then click on School Newspaper Interviews
The Simulation detail page still displays all the attempts. So the modal is too big.

**Comment by namduongkh** [comment]
PR? https://github.com/khailamconsulting/khailamconsulting.github.io/pull/57

**Comment by pmquan** [comment]
Thank you. It is working well.
