### ISSUE TITLE
StudentView gives invalid query

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#49]
It seems after you open a studentView page, then go back, navigate to another page like settings, archived class. Then you go back to the classView, click to view the student detail - this will call the student API without a classId.

Step to reproduce
+ Go to Class View, click on Alelo Everyone Learning
+ Click on the student name "Lewis".
+ Click back icon.
+ Click Archived tab, then Settings tab.
+ Click to Class View tab. Then click on that student again.

**Comment by namduongkh** [comment]
@pmquan 
Worked
Could you please take a look and close?
