### ISSUE TITLE
Need suggestion on the StudentDetailView page

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#50]
Right now, the original document indicates that this page uses the Tab style for the course list. But it doesn't seem to work well if there are many classes or classes with a long name.

Shall we switch them to a dropdown selection box for this?

**Comment by namduongkh** [comment]
We can use select box:
<img width="294" alt="Screen Shot 2020-11-28 at 6 12 36 PM" src="https://user-images.githubusercontent.com/17775345/100514238-8ffcb400-31a5-11eb-85c1-50140d4a09d0.png">
Or horizontal scroll tab bar
<img width="761" alt="Screen Shot 2020-11-28 at 6 11 39 PM" src="https://user-images.githubusercontent.com/17775345/100514249-a4d94780-31a5-11eb-82ae-8217ef0c8bdc.png">

**Comment by pmquan** [comment]
If it is easy, please try to implement the horizontal scroll tab bar first.

Thank you!

**Comment by pmquan** [comment]
The interface is a bit buggy. See this screenshot: 

https://share.alelo.com/index.php/s/ME5fS69iREqvtM8

**Comment by dunghuynhtrung1987** [comment]
@pmquan 
Yes, i have fixing

**Comment by pmquan** [comment]
@dunghuynhtrung1987 Hi, can you sort the tab by the course name? Thank you.

**Comment by dunghuynhtrung1987** [comment]
@namduongkh, pls help me take care this issue.

**Comment by namduongkh** [comment]
@pmquan 
PR: https://github.com/khailamconsulting/khailamconsulting.github.io/pull/60
