### ISSUE TITLE
Class Viewer - Show page

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#6]
- Name
- Start - End (JQuery Calendar)
- Select Courses (Courses List from AJAX query)
- Student List (Ajax)
- Add students button
- Delete class button

<img width="945" alt="Screen Shot 2020-10-02 at 12 11 07 AM" src="https://user-images.githubusercontent.com/1320349/94841135-c9ce6a00-0443-11eb-9435-9b17b84bd9d1.png">

**Comment by dunghuynhtrung1987** [comment]
Click **basic English** show Course Information (Pop-up Screen)

<img width="622" alt="Screen Shot 2020-10-03 at 9 39 01 AM" src="https://user-images.githubusercontent.com/48272651/94981442-a0edc800-055c-11eb-8c68-e7ed8621241c.png">

Click **Delete Your Class, Remove Student(s), Resend Invitation(s), Add Students, Invite** button show pop-up

<img width="725" alt="Screen Shot 2020-10-03 at 9 42 28 AM" src="https://user-images.githubusercontent.com/48272651/94981522-24a7b480-055d-11eb-967a-9aaef5602734.png">
<img width="537" alt="Screen Shot 2020-10-03 at 10 00 06 AM" src="https://user-images.githubusercontent.com/48272651/94981830-92ed7680-055f-11eb-84a0-336c6a92425c.png">
<img width="547" alt="Screen Shot 2020-10-03 at 10 00 21 AM" src="https://user-images.githubusercontent.com/48272651/94981836-9c76de80-055f-11eb-949a-5201e8280651.png">
<img width="565" alt="Screen Shot 2020-10-03 at 10 00 36 AM" src="https://user-images.githubusercontent.com/48272651/94981839-a4cf1980-055f-11eb-8ea4-900464fff6c0.png">
<img width="558" alt="Screen Shot 2020-10-03 at 10 00 58 AM" src="https://user-images.githubusercontent.com/48272651/94981846-b1537200-055f-11eb-8f51-a699c18ff310.png">
<img width="542" alt="Screen Shot 2020-10-03 at 10 00 52 AM" src="https://user-images.githubusercontent.com/48272651/94981848-b87a8000-055f-11eb-9bd6-28a91b6a1f62.png">

Click **Name** on section Student List show StudentPage.html and show pop up when click name Course 

<img width="836" alt="Screen Shot 2020-10-03 at 10 04 37 AM" src="https://user-images.githubusercontent.com/48272651/94981899-33dc3180-0560-11eb-91c2-cc915d43f5f9.png">
<img width="793" alt="Screen Shot 2020-10-03 at 10 05 04 AM" src="https://user-images.githubusercontent.com/48272651/94981906-48b8c500-0560-11eb-9597-c66b19939dfd.png">
