### ISSUE TITLE
Create A New Class/Select an institution doesn't change the text

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#79]
When I select the "Institution" drop-down, the displayed text still displays "Institution" instead of the item name. Can you change it please?

**Comment by namduongkh** [comment]
@pmquan fix in https://github.com/khailamconsulting/khailamconsulting.github.io/pull/81

**Comment by pmquan** [comment]
Thank you. Fixed! Confirmed.
