### ISSUE TITLE
Settings Page 

### ISSUE THREAD

**Issue by rauxalach** [khailamconsulting/khailamconsulting.github.io#8]
Show Profile.
- Change password button.
<img width="766" alt="Screen Shot 2020-10-02 at 12 14 00 AM" src="https://user-images.githubusercontent.com/1320349/94841450-3e090d80-0444-11eb-936a-1a0d9e0b7297.png">

**Comment by dunghuynhtrung1987** [comment]
Click change password button show expand form
<img width="684" alt="Screen Shot 2020-10-03 at 9 34 27 AM" src="https://user-images.githubusercontent.com/48272651/94981396-3177d880-055c-11eb-8dcf-471f6d9cc291.png">
