### ISSUE TITLE
Active Class View - broken layout when displaying more than 5 classes.

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#80]
If there are many classes, the layout is broken.

Can we paginate it?

![image](https://user-images.githubusercontent.com/5755393/106144179-b2209d00-6128-11eb-9d0b-56a922b09367.png)

**Comment by namduongkh** [comment]
@pmquan 
we're using the scroll bar instead of the paginator as the requirement.
<img width="1259" alt="Screen Shot 2021-01-28 at 10 30 11 PM" src="https://user-images.githubusercontent.com/17775345/106160614-995fc800-61b8-11eb-8583-b63932776920.png">

**Comment by namduongkh** [comment]
@pmquan could you please provide the testing site URL?

**Comment by pmquan** [comment]
The problem happens after go to the Class Viewer.

So try to view a Class, then go back to the ActiveClass List, the problem will appear.

I will work on the way that you guys can use our dev system.

**Comment by namduongkh** [comment]
@pmquan PR pls https://github.com/khailamconsulting/khailamconsulting.github.io/pull/84

**Comment by pmquan** [comment]
Fixed
