### ISSUE TITLE
Delete Class - Display record incorrectly

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#82]
After delete the class, the Dashboard shall reload the ClassList.

**Comment by namduongkh** [comment]
@pmquan 
The error CORS is appearing now, please config the API side to accept request from `http://localhost:8888`
<img width="1473" alt="Screen Shot 2021-01-30 at 8 27 17 PM" src="https://user-images.githubusercontent.com/17775345/106358005-2f702b80-633c-11eb-965c-06705655ae39.png">

**Comment by pmquan** [comment]
Fixed
