### ISSUE TITLE
Class Viewer: Edit/Add Courses/Add Students

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#83]
Can you please separate those POST call into 3 separate API calls?

1. Edit: POST Data: { name: value, institution: value, startDate: value, endDate: value } - endpoint: class/update/id
2. Add Courses: POST Data { selectedCourses: [ "courseSelectedID1", "courseSelectedID2" ] } - endpoint: class/addcourse/id
3. Add Students: POST Data { students: [ "email1", "email2" ] } - endpoint: class/addstudent/id

The form must validate email address and display any error (see the Create a new class button)

After POST the data; if json.success = true; call class/view/id again and update the Class View layout (from data.id). All above API will return

{ 
 success: true,
 data: { id: ClassID }
}

**Comment by namduongkh** [comment]
@pmquan https://github.com/khailamconsulting/khailamconsulting.github.io/pull/86

**Comment by pmquan** [comment]
Confirmed.
