### ISSUE TITLE
Instructor Dashboard - ClassView - Only allow to view detail for the actual user

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#87]
Now the student will have the attribute: "isUser".

If isUser is not true, please don't give the hyperlink or allow to click to view the user detail.

**Comment by namduongkh** [comment]
@pmquan 
when clicking on this, right?
<img width="1080" alt="Screen Shot 2021-02-01 at 9 51 42 PM" src="https://user-images.githubusercontent.com/17775345/106474720-c45b5c00-64d7-11eb-8dd1-c2d03b11ebbf.png">

**Comment by pmquan** [comment]
Yes. If isUser equals to false, don't display the hyperlink.

**Comment by namduongkh** [comment]
@pmquan https://github.com/khailamconsulting/khailamconsulting.github.io/pull/94
