### ISSUE TITLE
Loading page after submitting the request

### ISSUE THREAD

**Issue by pmquan** [khailamconsulting/khailamconsulting.github.io#89]
When you submit a request (create a class, class deletion, etc..) , it will just close the popup. It might make the user frustrated.

Example:
User tries to delete a class.
They hit the delete button, then confirm. Then it will kick back to the Class view page, sometimes the deletion request takes up to 5 seconds. So the user might click delete button again.

Suggest, can we make a "Please hold on while we are processing your request" popup until the request has the return value?

**Comment by namduongkh** [comment]
@pmquan we can add a loader layout like that:
<img width="1197" alt="Screen Shot 2021-02-01 at 9 46 08 PM" src="https://user-images.githubusercontent.com/17775345/106473931-f5875c80-64d6-11eb-9d61-b446c29bd269.png">

open it when load ajax submit and can re-use many places

**Comment by pmquan** [comment]
Yes, please implement this to every single ajax call.

**Comment by namduongkh** [comment]
@pmquan https://github.com/khailamconsulting/khailamconsulting.github.io/pull/93
